#!/bin/sh
######################################################################
# The /etc/dhclient-enter-hooks script is run by the ISC DHCP client's standard
# update script whenever dhclient obtains or renews an address. 

PATH=/usr/sbin:${PATH}
case "$new_ip_address" in
10.*)   	;;
172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].*)	;;
192.168.*)	;;
*)
	logger -t dhclient IP address changed to $new_ip_address
	ddclient -daemon=0 -syslog -use=ip -ip=$new_ip_address >/dev/null 2>&1
	;;
esac
